baseURL: https://tylermumford.com/
disablePathToLower: true
languageCode: en-us
title: Tyler Mumford
theme: hyde
description: Web Developer
publishDir: docs

markup:
  goldmark:
    renderer:
      unsafe: true
      # This is about allowing raw html in .md files.
      # Since they're all hand-written, I believe
      # this is safe to do.

taxonomies:
    tag: "tags"

params:
    description: Web Developer
    layoutReverse: true
    themeColor: theme-base-0b

menu:
    main:
        - Name: Projects
          URL: /project/
          Weight: 2
        - Name: Contact
          URL: /page/contact/
          Weight: 3
