title = "Tyler Mumford"

base_url = "https://tylermumford.com"

# Yes, RSS is fantastic.
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[extra]

# Only have analytics record data for the public hostname
public_hostname = "tylermumford.com"
